name: Release

on:
  push:
    tags:
      - 'v*'  # semantic release tags, e.g. v1.0.0, v2.1.3

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Compile PDF
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex

    - name: Rename PDF for release
      run: mv main.pdf white-book.pdf

    - name: Attach PDF to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: white-book.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

